version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - goos:
      - linux
      - windows
    goarch:
      - amd64
      - '386'
    ldflags:
      - -s -w

    overrides:
      - goos: windows
        goarch: amd64
        goamd64: v1
        ldflags:
          - -s -w -extldflags "-static"

      - goos: windows
        goarch: '386'
        ldflags:
          - -s -w -extldflags "-static"

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

upx:
  - enabled: true
    compress: '9'
