# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          lfs: 'true'

    - name: Download necessary packages for 64 bits and 32 bits computers
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install gcc libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev \
        pkg-config gcc-multilib libc6-dev:i386 libgl1-mesa-dev:i386 libxcursor-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libxrandr-dev:i386 \
        libxxf86vm-dev:i386 libasound2-dev:i386 -y



    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.5"

    - name: Build
      run: go build -v ./...
