# .github/workflows/release.yml
name: goreleaser

on:
  workflow_run:
    workflows: ["Build test"]
    branches: [main]
    types:
      - completed

  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: 'true'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Download necessary packages
        run: |
            sudo dpkg --add-architecture i386
            sudo apt update
            sudo apt install gcc libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev \
            pkg-config gcc-multilib libc6-dev:i386 libgl1-mesa-dev:i386 libxcursor-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libxrandr-dev:i386 \
            libxxf86vm-dev:i386 libasound2-dev:i386 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 upx -y

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "-> ~2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
