# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          lfs: 'true'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.5"

    - name: Build for Windows
      run: CC=gcc-mingw-w64-x86-64 go build -v ./...
